CREATE OR REPLACE VIEW CLIENT_ORDER AS 
SELECT o.id, o.status, o.distance FROM ORDERS o;

CREATE OR REPLACE VIEW CURIER_ORDER AS 
SELECT u.NAME, u.PHONE_NUMBER, o.ID, o.ID_FROM,o.ID_TO, o.DISTANCE, o.STATUS
    FROM ORDERS o
    JOIN USERS u ON o.ID_CLIENT=u.ID
    WHERE o.status IS NULL;
